In [2]:
import pandas as pd
import numpy as np

sdl = pd.read_excel('售电量.xlsx')
sdl = sdl.fillna(0)
sdl

FileNotFoundError: [Errno 2] No such file or directory: '售电量.xlsx'

In [ ]:
sdl.describe()

本年累计数         万千瓦时
count  1.381000e+03  1381.000000
mean   1.579258e+05    15.792576
std    2.063528e+05    20.635276
min   -9.838687e+04    -9.838687
25%    5.272521e+04     5.272521
50%    1.040173e+05    10.401733
75%    1.824760e+05    18.247605
max    2.363284e+06   236.328414

In [ ]:
sdl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1381 entries, 0 to 1380
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   组织名称    1381 non-null   object 
 1   本年累计数   1381 non-null   float64
 2   万千瓦时    1381 non-null   float64
dtypes: float64(2), object(1)
memory usage: 32.5+ KB


In [ ]:
sdl_max = np.max(sdl['万千瓦时'])
sdl_min = np.min(sdl['万千瓦时'])
bins_step = (sdl_max - sdl_min) / 30
bins = [i for i in np.arange(sdl_min, sdl_max, bins_step)]
bins.append(sdl_max)
bins

[-9.838687,
 -1.633116966666666,
 6.572453066666668,
 14.778023100000002,
 22.983593133333336,
 31.189163166666667,
 39.394733200000005,
 47.60030323333334,
 55.80587326666667,
 64.0114433,
 72.21701333333334,
 80.42258336666669,
 88.6281534,
 96.83372343333335,
 105.03929346666669,
 113.24486350000001,
 121.45043353333335,
 129.6560035666667,
 137.8615736,
 146.06714363333336,
 154.27271366666668,
 162.47828370000002,
 170.68385373333336,
 178.88942376666668,
 187.09499380000003,
 195.30056383333337,
 203.5061338666667,
 211.71170390000003,
 219.91727393333338,
 228.1228439666667,
 236.328414]

In [ ]:
np.round(bins)

array([-10.,  -2.,   7.,  15.,  23.,  31.,  39.,  48.,  56.,  64.,  72.,
        80.,  89.,  97., 105., 113., 121., 130., 138., 146., 154., 162.,
       171., 179., 187., 195., 204., 212., 220., 228., 236.])

In [ ]:
bin_idx = []
for i in sdl['万千瓦时']:
    if i == bins[0]:
        bin_idx.append(0)
        continue
    for j in range(1, len(bins)):
        if i > bins[j - 1] and i <= bins[j]:
            bin_idx.append(j - 1)
bins_count = np.bincount(bin_idx)
bins_count

array([  2, 436, 485, 203, 108,  55,  29,  11,  15,   8,   4,   4,   4,
         3,   3,   1,   2,   1,   0,   2,   1,   0,   0,   0,   0,   0,
         0,   2,   0,   2], dtype=int64)

In [ ]:
bins_count_avg = np.average(bins_count) / 2
bins_count_avg

23.016666666666666

In [ ]:
new_bins = [bins[0]]
new_bins_count = []
acc = 0
for i in range(len(bins_count)):
    acc += bins_count[i]
    if acc > bins_count_avg:
        new_bins.append(bins[i + 1])
        new_bins_count.append(acc)
        acc = 0
if acc != 0:
    new_bins.append(bins[len(bins) - 1])
    new_bins_count.append(acc)
new_bins

[-9.838687,
 6.572453066666668,
 14.778023100000002,
 22.983593133333336,
 31.189163166666667,
 39.394733200000005,
 47.60030323333334,
 64.0114433,
 113.24486350000001,
 236.328414]

In [ ]:
np.round(new_bins)

array([-10.,   7.,  15.,  23.,  31.,  39.,  48.,  64., 113., 236.])

In [ ]:
new_bins_count

[438, 485, 203, 108, 55, 29, 26, 26, 11]